name: image-uploader-api

services:
  app:
    build:
      context: .
      target: dev
    container_name: api
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /usr/src/app
    ports:
      - 3333:3333
    env_file:
      - .env
    environment:
      CI: "true"
      DB_URL: "postgresql://postgres:postgres@postgres:5432/image_uploader"
    command: sh -c "pnpm install --frozen-lockfile --store-dir /pnpm/store --config.confirmModulesPurge=false && pnpm run db:migrate && pnpm run dev"
    volumes:
      - .:/usr/src/app
      - app-node-modules:/usr/src/app/node_modules
      - pnpm-store:/pnpm/store
    networks:
      - image-uploader

  postgres:
    container_name: postgres
    image: postgres:18.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "image_uploader"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pg-data:/var/lib/postgresql
      - ./docker:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d image_uploader"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - image-uploader

volumes:
  app-node-modules: {}
  pg-data: {}
  pnpm-store: {}

networks:
  image-uploader:
    driver: bridge
